"""empty message

Revision ID: 18facd8f7628
Revises: 9ddab84e98d1
Create Date: 2020-12-08 17:56:23.634413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18facd8f7628'
down_revision = '9ddab84e98d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
